# Generated by Django 4.0.1 on 2022-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advansed',
            field=models.BooleanField(default=False, verbose_name='advance'),
        ),
        migrations.AddField(
            model_name='user',
            name='beginner',
            field=models.BooleanField(default=False, verbose_name='beginner'),
        ),
        migrations.AddField(
            model_name='user',
            name='elemantry',
            field=models.BooleanField(default=False, verbose_name='elemantry'),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate',
            field=models.BooleanField(default=False, verbose_name='inter'),
        ),
        migrations.AddField(
            model_name='user',
            name='pre',
            field=models.BooleanField(default=False, verbose_name='pre'),
        ),
        migrations.AddField(
            model_name='user',
            name='upper',
            field=models.BooleanField(default=False, verbose_name='upper'),
        ),
    ]
