# Generated by Django 4.0.1 on 2022-01-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_advansed_remove_user_beginner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daraja',
            field=models.CharField(choices=[('beginner', 'baginner'), ('elemantry', 'elemantry'), ('pre', 'pre'), ('inter', 'inter'), ('upper', 'upper')], default='beginner', max_length=30, null=True),
        ),
    ]
