# Generated by Django 4.0.1 on 2022-01-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vaqt',
        ),
    ]
