# Generated by Django 4.0.1 on 2022-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vaqt',
            field=models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default=False, max_length=10, null=True),
        ),
    ]
